const BASE_DRUG_NAMES = [
  "Paracetamol",
  "Ibuprofen",
  "Amoxicillin",
  "Azithromycin",
  "Cefixime",
  "Ciprofloxacin",
  "Metronidazole",
  "Doxycycline",
  "Levofloxacin",
  "Clarithromycin",
  "Omeprazole",
  "Pantoprazole",
  "Esomeprazole",
  "Rabeprazole",
  "Lansoprazole",
  "Famotidine",
  "Ranitidine",
  "Domperidone",
  "Ondansetron",
  "Metoclopramide",
  "Loperamide",
  "Oral Rehydration Salts",
  "Mebendazole",
  "Albendazole",
  "Praziquantel",
  "Acyclovir",
  "Valacyclovir",
  "Fluconazole",
  "Itraconazole",
  "Ketoconazole",
  "Nystatin",
  "Cetirizine",
  "Loratadine",
  "Fexofenadine",
  "Chlorpheniramine",
  "Diphenhydramine",
  "Montelukast",
  "Salbutamol",
  "Budesonide",
  "Beclomethasone",
  "Ipratropium",
  "Tiotropium",
  "Prednisolone",
  "Dexamethasone",
  "Hydrocortisone",
  "Methylprednisolone",
  "Aspirin",
  "Clopidogrel",
  "Atorvastatin",
  "Rosuvastatin",
  "Simvastatin",
  "Losartan",
  "Valsartan",
  "Telmisartan",
  "Amlodipine",
  "Nifedipine",
  "Enalapril",
  "Lisinopril",
  "Ramipril",
  "Atenolol",
  "Metoprolol",
  "Bisoprolol",
  "Propranolol",
  "Hydrochlorothiazide",
  "Furosemide",
  "Spironolactone",
  "Chlorthalidone",
  "Digoxin",
  "Isosorbide Mononitrate",
  "Nitroglycerin",
  "Warfarin",
  "Rivaroxaban",
  "Apixaban",
  "Heparin",
  "Enoxaparin",
  "Metformin",
  "Glibenclamide",
  "Glimepiride",
  "Gliclazide",
  "Sitagliptin",
  "Vildagliptin",
  "Empagliflozin",
  "Dapagliflozin",
  "Insulin Regular",
  "Insulin NPH",
  "Insulin Glargine",
  "Levothyroxine",
  "Carbimazole",
  "Methimazole",
  "Propylthiouracil",
  "Calcium Carbonate",
  "Vitamin D3",
  "Iron Folic Acid",
  "Ferrous Sulfate",
  "Vitamin B Complex",
  "Vitamin C",
  "Vitamin B12",
  "Folic Acid",
  "Zinc Sulfate",
  "Magnesium Oxide",
  "Multivitamin",
  "Calcium + Vitamin D",
  "Diclofenac",
  "Naproxen",
  "Mefenamic Acid",
  "Ketorolac",
  "Tramadol",
  "Codeine",
  "Morphine",
  "Gabapentin",
  "Pregabalin",
  "Amitriptyline",
  "Nortriptyline",
  "Sertraline",
  "Fluoxetine",
  "Escitalopram",
  "Duloxetine",
  "Venlafaxine",
  "Clonazepam",
  "Diazepam",
  "Alprazolam",
  "Haloperidol",
  "Risperidone",
  "Olanzapine",
  "Quetiapine",
  "Sodium Valproate",
  "Carbamazepine",
  "Phenytoin",
  "Levetiracetam",
  "Lamotrigine",
  "Topiramate",
  "Allopurinol",
  "Colchicine",
  "Methotrexate",
  "Sulfasalazine",
  "Hydroxychloroquine",
  "Azathioprine",
  "Cyclophosphamide",
  "Ceftriaxone",
  "Ceftazidime",
  "Piperacillin Tazobactam",
  "Amoxicillin Clavulanate",
  "Meropenem",
  "Imipenem",
  "Gentamicin",
  "Amikacin",
  "Linezolid",
  "Vancomycin",
  "Co-trimoxazole",
  "Nitrofurantoin",
  "Fosfomycin",
  "Tamsulosin",
  "Finasteride",
  "Sildenafil",
  "Dutasteride",
  "Oxybutynin",
  "Mirabegron",
  "Tranexamic Acid",
  "Ethamsylate",
  "Misoprostol",
  "Oxytocin",
  "Methylergometrine",
  "Combined Oral Contraceptive",
  "Progesterone",
  "Medroxyprogesterone",
  "Clotrimazole",
  "Miconazole",
  "Terbinafine",
  "Permethrin",
  "Benzyl Benzoate",
  "Hydrogen Peroxide",
  "Povidone Iodine",
  "Chlorhexidine",
  "Silver Sulfadiazine",
  "Mupirocin",
  "Fusidic Acid",
  "Tetracycline Eye Ointment",
  "Artificial Tears",
  "Timolol Eye Drops",
  "Latanoprost Eye Drops",
  "Brimonidine Eye Drops",
  "Dorzolamide Eye Drops",
  "Acetazolamide",
  "Bromhexine",
  "Ambroxol",
  "Dextromethorphan",
  "Guaifenesin",
  "Pseudoephedrine",
  "Phenylephrine",
  "Xylometazoline",
  "Normal Saline Nasal Drops",
  "Oral Zinc",
  "ORS Pediatric",
  "Paracetamol Pediatric",
  "Ibuprofen Pediatric",
  "Amoxicillin Pediatric",
  "Cefixime Pediatric",
  "Azithromycin Pediatric",
  "Nystatin Oral",
  "Lactulose",
  "Bisacodyl",
  "Senna",
  "Polyethylene Glycol",
  "Docusate Sodium",
  "Glycerin Suppository",
  "Sodium Bicarbonate",
  "Potassium Chloride",
  "Calcium Gluconate",
  "Magnesium Sulfate",
  "Thiamine",
  "Pyridoxine",
  "Riboflavin",
  "Niacin",
  "Biotin",
  "Cyanocobalamin",
  "Amlodipine + Valsartan",
  "Losartan + Hydrochlorothiazide",
  "Metformin + Glimepiride",
  "Metformin + Sitagliptin",
  "Paracetamol + Caffeine",
  "Diclofenac Gel",
  "Ketoprofen Gel",
  "Lidocaine Gel",
  "Lidocaine Injection",
  "Bupivacaine Injection",
  "Adrenaline Injection",
  "Atropine Injection",
  "Fentanyl Injection",
  "Midazolam Injection",
  "Propofol Injection",
  "Cefotaxime",
  "Cefuroxime",
  "Cefalexin",
  "Erythromycin",
  "Roxithromycin",
  "Tinidazole",
  "Secnidazole",
  "Artemether Lumefantrine",
  "Artesunate",
  "Chloroquine",
  "Primaquine",
  "Quinine",
  "Ivermectin",
  "Dapsone",
  "Rifampicin",
  "Isoniazid",
  "Pyrazinamide",
  "Ethambutol",
  "Levodopa Carbidopa",
  "Donepezil",
  "Memantine",
  "Ranitidine Syrup",
  "Omeprazole Suspension",
  "Pantoprazole Injection",
  "Insulin Lispro",
  "Insulin Aspart",
  "Norepinephrine Injection",
  "Dopamine Injection",
  "Dobutamine Injection",
  "Mannitol",
  "Acetylcysteine",
  "Ursodeoxycholic Acid",
  "Mesalamine",
  "Hyoscine Butylbromide",
  "Dicyclomine",
  "Rifaximin",
  "Saccharomyces boulardii",
  "Probiotic Capsules",
  "Tobramycin Eye Drops",
  "Moxifloxacin Eye Drops",
  "Ofloxacin Eye Drops",
  "Ciprofloxacin Eye Drops",
  "Ear Drops Combination",
  "Betamethasone Cream",
  "Hydrocortisone Cream",
  "Clobetasol Cream",
  "Tacrolimus Ointment",
  "Heparinoid Cream",
  "Calamine Lotion",
  "Aloe Vera Gel",
  "Ornidazole",
  "Candesartan",
  "Irbesartan",
  "Perindopril",
  "Nebivolol",
  "Ivabradine",
  "Fenofibrate",
  "Ezetimibe",
  "Pioglitazone",
  "Linagliptin",
  "Acarbose",
  "Canagliflozin",
  "Thyroxine",
  "Prednisone",
  "Deflazacort",
  "Baclofen",
  "Tizanidine",
  "Cyclobenzaprine",
  "Etoricoxib",
  "Celecoxib",
  "Meloxicam",
  "Piroxicam",
  "Indomethacin",
  "Dexketoprofen",
  "Tapentadol",
  "Buprenorphine",
  "Naloxone",
  "Pantoprazole + Domperidone",
  "Rabeprazole + Levosulpiride",
  "Esomeprazole + Itopride",
  "Levosulpiride",
  "Itopride",
  "Febuxostat",
  "Probenecid",
  "Rasburicase",
  "Terazosin",
  "Alfuzosin",
  "Solifenacin",
  "Tolterodine",
  "Nitrofurazone Cream",
  "Methyl Salicylate Ointment",
  "Benzocaine Gel",
  "Oral Lidocaine Viscous",
  "Sodium Chloride IV",
  "Dextrose 5% IV",
  "Dextrose Saline IV",
  "Ringer Lactate",
  "Cefoperazone Sulbactam",
  "Sulbactam Ampicillin",
  "Tigecycline",
  "Colistin",
  "Teicoplanin",
  "Metformin XR",
  "Gliclazide MR",
  "Aspirin Enteric Coated",
  "Clopidogrel + Aspirin",
  "Telmisartan + Amlodipine",
  "Amlodipine + Atenolol",
  "Losartan + Amlodipine",
  "Rosuvastatin + Ezetimibe",
  "Atorvastatin + Fenofibrate",
  "Insulin Premix 30/70",
  "Insulin Degludec",
  "Glucagon Injection",
  "Magaldrate + Simethicone",
  "Sucralfate",
  "Bismuth Subsalicylate",
  "Racecadotril",
  "Ondansetron ODT",
  "Prochlorperazine",
  "Promethazine",
  "Levocetirizine",
  "Desloratadine",
  "Bilastine",
  "Rupatadine",
  "Budesonide Nasal Spray",
  "Fluticasone Nasal Spray",
  "Mometasone Nasal Spray",
  "Salmeterol + Fluticasone",
  "Formoterol + Budesonide",
  "Tiotropium + Olodaterol",
  "Glycopyrrolate",
  "Theophylline",
  "Aminophylline",
  "Montelukast + Levocetirizine",
  "Orlistat",
  "Phentermine",
  "Liraglutide",
  "Semaglutide",
  "Empagliflozin + Metformin",
  "Dapagliflozin + Metformin",
  "Sitagliptin + Metformin",
  "Vildagliptin + Metformin",
  "Linagliptin + Metformin",
  "Ferrous Ascorbate",
  "Iron Sucrose",
  "Folic Acid + Iron",
  "Methylcobalamin",
  "Methylcobalamin + Pregabalin",
  "Methylcobalamin + Alpha Lipoic Acid",
  "Alpha Lipoic Acid",
  "Coenzyme Q10",
  "Omega 3",
  "Calcium Citrate",
  "Vitamin K2",
  "Vitamin E",
  "Selenium",
  "Copper Supplement",
  "Lutein",
  "Cranberry Extract",
  "Potassium Citrate",
  "Sodium Citrate",
  "Urinary Alkalizer",
  "Leuprolide",
  "Tamoxifen",
  "Anastrozole",
  "Letrozole",
  "Aromatase Inhibitor",
  "Bicalutamide",
  "Docetaxel",
  "Paclitaxel",
  "Cyclophosphamide Injection",
  "Ondansetron Injection",
  "Granisetron",
  "Palonosetron",
  "Filgrastim",
  "Erythropoietin",
  "Folic Acid Injection",
  "Vitamin B Complex Injection",
  "Tranexamic Acid Injection",
  "Diclofenac Injection",
  "Paracetamol Infusion",
  "Meropenem Injection",
  "Piperacillin Tazobactam Injection",
  "Vancomycin Injection",
  "Colistin Injection",
  "Norfloxacin",
  "Levofloxacin Eye Drops",
  "Moxifloxacin Tablet",
  "Aztreonam",
  "Clindamycin",
  "Lincomycin",
  "Rifaximin + Lactobacillus",
  "Sacubitril Valsartan",
  "Diltiazem",
  "Verapamil",
  "Nicorandil",
  "Trimetazidine",
  "Ranolazine",
  "Eplerenone",
  "Torsemide",
  "Bumetanide",
  "Methyldopa",
  "Hydralazine",
  "Minoxidil",
  "Phenobarbital",
  "Clobazam",
  "Oxcarbazepine",
  "Zonisamide",
  "Lacosamide",
  "Ropinirole",
  "Pramipexole",
  "Trihexyphenidyl",
  "Benztropine",
  "Meclizine",
  "Betahistine",
  "Cinnarizine",
  "Flunarizine",
  "Sumatriptan",
  "Rizatriptan",
  "Topical Minoxidil",
  "Ketoconazole Shampoo",
  "Coal Tar Shampoo",
  "Ciclopirox",
  "Adapalene",
  "Benzoyl Peroxide",
  "Isotretinoin",
  "Doxycycline Acne",
  "Clindamycin Gel",
  "Azelaic Acid",
  "Hydroquinone",
  "Metformin SR",
  "Glibenclamide + Metformin",
  "Pioglitazone + Metformin",
  "Glycopyrrolate Inhaler",
  "Umeclidinium",
  "Aclidinium",
  "Nintedanib",
  "Pirfenidone",
  "Oseltamivir",
  "Favipiravir",
  "Remdesivir",
  "Zinc + Vitamin C",
  "Propranolol LA",
  "Metoprolol XL",
  "Atenolol + Chlorthalidone",
  "Hydrochlorothiazide + Amiloride",
  "Spironolactone + Furosemide",
  "Lactulose Syrup",
  "Senna Syrup",
  "Bisacodyl Suppository",
  "Glycerin Pediatric Suppository",
  "Domperidone Syrup",
  "Ondansetron Syrup",
  "Ibuprofen Suspension",
  "Paracetamol Suspension",
  "Amoxicillin Suspension",
  "Cefixime Suspension",
  "Azithromycin Suspension",
  "ORS Zinc Combo",
  "Vitamin D Drops",
  "Iron Syrup",
  "Calcium Syrup",
  "Multivitamin Syrup",
  "Cough Syrup Expectorant",
  "Cough Syrup Antitussive"
];

const DOSAGE_OPTIONS = [
  "2.5mg",
  "5mg",
  "10mg",
  "20mg",
  "25mg",
  "40mg",
  "50mg",
  "75mg",
  "100mg",
  "200mg",
  "250mg",
  "500mg",
  "650mg",
  "1g",
  "5ml"
];

const TYPE_OPTIONS = ["Tablet", "Capsule", "Syrup", "Injection", "Drops", "Ointment"];
const FREQUENCY_OPTIONS = ["1x1", "1x2", "1x3", "2x2", "SOS"];
const MEAL_OPTIONS = ["Before food", "After food", "Anytime"];
const COMPANY_OPTIONS = [
  "Generic Pharma",
  "Global Med",
  "HealthCare Labs",
  "Trust Pharma",
  "Afghan Med",
  "City Pharma",
  "Nobel Healthcare",
  "Nova Drugs"
];

export const COMMON_MEDICINES_FRONTEND = Array.from({ length: 500 }, (_, index) => {
  const name = BASE_DRUG_NAMES[index % BASE_DRUG_NAMES.length];
  const mealTiming = MEAL_OPTIONS[index % MEAL_OPTIONS.length];
  const companyName = COMPANY_OPTIONS[index % COMPANY_OPTIONS.length];

  return {
    id: `local-${index + 1}`,
    genericName: name,
    name,
    companyName,
    mealTiming,
    amount: 0,
  };
});
